### ISSUE TITLE
error from explain

### ISSUE THREAD

**Issue by billnjcn111** [ModelOriented/survex#16] opened 2022-10-28 12:55 UTC
Hi, 
I got some nasty errors and hopefully authors can check into this.
something odd here: no error in model but in the explain step:
 model.src <- randomForestSRC::rfsrc(Surv(OS, status) ~ ., data = data) 
explain(model.src)
Error in grep("NODE", lns):(length(lns) - 2) : argument of length 0
In addition: Warning messages:
1: In if (substring(pattern, 1, 4) == "@rm_") { :
  the condition has length > 1 and only the first element will be used
2: In if (substring(pattern, 1, 1) == "@") { :
  the condition has length > 1 and only the first element will be used

**Comment by mikolajsp** [comment] 2022-10-28 13:02
Hello, I'm going to check on this, but can't seem to replicate your code. Can you include a reproducible example using `reprex::reprex(..., session_info = TRUE).`

**Comment by billnjcn111** [comment] 2022-10-28 13:12
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.4 (2021-02-15)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/New_York            
#>  date     2022-10-28                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source        
#>  cli           3.2.0   2022-02-14 [1] CRAN (R 4.0.5)
#>  crayon        1.4.1   2021-02-08 [1] CRAN (R 4.0.4)
#>  digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.4)
#>  ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.0.5)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.4)
#>  fansi         0.4.2   2021-01-15 [1] CRAN (R 4.0.4)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.0.4)
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.4)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.0.5)
#>  highr         0.8     2019-03-20 [1] CRAN (R 4.0.4)
#>  htmltools     0.5.2   2021-08-25 [1] CRAN (R 4.0.5)
#>  knitr         1.36    2021-09-29 [1] CRAN (R 4.0.5)
#>  lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.0.5)
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.4)
#>  pillar        1.7.0   2022-02-01 [1] CRAN (R 4.0.5)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.4)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.4)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.0.4)
#>  R.methodsS3   1.8.1   2020-08-26 [1] CRAN (R 4.0.3)
#>  R.oo          1.24.0  2020-08-26 [1] CRAN (R 4.0.3)
#>  R.utils       2.10.1  2020-08-26 [1] CRAN (R 4.0.4)
#>  reprex        1.0.0   2021-01-27 [1] CRAN (R 4.0.4)
#>  rlang         1.0.2   2022-03-04 [1] CRAN (R 4.0.5)
#>  rmarkdown     2.13    2022-03-10 [1] CRAN (R 4.0.5)
#>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.0.4)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.4)
#>  stringi       1.7.5   2021-10-04 [1] CRAN (R 4.0.5)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.4)
#>  styler        1.7.0   2022-03-13 [1] CRAN (R 4.0.5)
#>  tibble        3.1.0   2021-02-25 [1] CRAN (R 4.0.4)
#>  utf8          1.2.1   2021-03-12 [1] CRAN (R 4.0.4)
#>  vctrs         0.4.0   2022-03-30 [1] CRAN (R 4.0.5)
#>  withr         2.4.1   2021-01-26 [1] CRAN (R 4.0.4)
#>  xfun          0.30    2022-03-02 [1] CRAN (R 4.0.5)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.3)

**Comment by mikolajsp** [comment] 2022-10-28 13:20
Sorry for the misunderstanding. To debug this error I would need the output of

```
reprex::reprex({
# the code that causes
# the error goes here

} , session_info = TRUE).
```

**Comment by mikolajsp** [comment] 2023-02-10 08:50
Closing this because of no info. Feel free to reopen with additional output.

**Closed as not planned by mikolajsp** 2023-02-10 08:50 UTC
Labels: invalid ❕
